import test from "node:test";
import assert from "node:assert/strict";
import { DEFAULT_SLOT_REGISTRY, REGISTRY_VERSION_SET, UNIVERSAL_SLOT_TEMPLATES, auditTerminalState, capabilityCoverageProof, capabilityInstanceId, canonicalCapabilityKey, claimCoverageProof, claimSetFingerprint, createArchitectureAuthority, currentMigrationProjection, decisionInstanceId, migrateV4Context, propagateStaleTransaction, requirementFingerprint, resolveCriticality, slotRegistryCoverageProof, validateArtifactDag, validateEvidenceEdge, validateSpecClaimConformance } from "../src/requirements-v5/contracts.js";

const rule={relation:"directly_entails",sourceKind:"answer",targetKind:"requirement",maxDerivationDepth:1,allowedSourceClassifications:["product_requirement"],allowedTargetClassifications:["product_requirement"]};
const evidence=()=>createArchitectureAuthority({registries:{relationRules:[rule],entailmentRules:[{entailmentRuleId:"r",sourceKind:"answer",targetKind:"requirement",sourceValueSchemaId:"enum",targetValueSchemaId:"enum",maxDerivationDepth:1}]},revisions:[{revisionId:"r1",currentness:"current",kind:"answer",classification:"product_requirement",scopeKey:"s",evidenceText:"A",valueSchemaId:"enum"}],targets:[{id:"t",currentness:"current",kind:"requirement",classification:"product_requirement",scopeKey:"s",valueSchemaId:"enum"}],evidenceEdges:[{edgeId:"e",currentness:"current",sourceRevisionId:"r1",targetId:"t",relation:"directly_entails",targetScopeKey:"s",evidenceSpan:"A",derivationDepth:1,entailmentRuleId:"r"}]});
const registry=()=>({registryVersion:REGISTRY_VERSION_SET.slotTemplate,semanticRegistryVersion:REGISTRY_VERSION_SET.coreUserValuePattern,slotTemplates:[...UNIVERSAL_SLOT_TEMPLATES.map(slotTemplateId=>({slotTemplateId,slotClass:"universal",registryVersion:REGISTRY_VERSION_SET.slotTemplate})),{slotTemplateId:"recipe",slotClass:"core_value_pattern",registryVersion:REGISTRY_VERSION_SET.slotTemplate}],coreUserValuePatterns:[{coreUserValuePatternId:"recipe",registryVersion:REGISTRY_VERSION_SET.coreUserValuePattern,requiredSlotTemplateIds:["recipe"]}]});

test("identity distinguishes null and empty collections",()=>{const a=canonicalCapabilityKey({capabilityTypeId:"c",managedObjectIds:null,actorIds:[],parentCapabilityInstanceId:null,phaseKindId:null}),b=canonicalCapabilityKey({capabilityTypeId:"c",managedObjectIds:[],actorIds:[],parentCapabilityInstanceId:null,phaseKindId:null});assert.notDeepEqual(a,b);assert.equal(capabilityInstanceId({...a,label:"x"}),capabilityInstanceId({...a,label:"y"}));assert.notEqual(decisionInstanceId({decisionTypeId:"d",capabilityInstanceId:"c",managedObjectIds:null,actorIds:[],phaseKindId:null},{globalScopeAllowed:true}),decisionInstanceId({decisionTypeId:"d",capabilityInstanceId:"c",managedObjectIds:[],actorIds:[],phaseKindId:null},{globalScopeAllowed:true}));});

test("evidence registry and ledgers reject caller-forged relation, scope, span, classification and conflict",()=>{const a=evidence();assert.equal(validateEvidenceEdge({authority:a,edgeId:"e"}).accepted,true);a.ledgers.evidenceEdges.get("e").relation="fake";assert.equal(validateEvidenceEdge({authority:a,edgeId:"e"}).accepted,false);a.ledgers.evidenceEdges.get("e").relation="directly_entails";a.ledgers.evidenceEdges.get("e").targetScopeKey="fake";assert.equal(validateEvidenceEdge({authority:a,edgeId:"e"}).accepted,false);a.ledgers.evidenceEdges.get("e").targetScopeKey="s";a.ledgers.evidenceEdges.get("e").evidenceSpan="";assert.equal(validateEvidenceEdge({authority:a,edgeId:"e"}).accepted,false);a.ledgers.evidenceEdges.get("e").evidenceSpan="A";a.ledgers.revisions.get("r1").classification="implementation_proposal";assert.equal(validateEvidenceEdge({authority:a,edgeId:"e",explicitStructuredAnswer:true}).accepted,false);});

test("slot registry and actual slot ledger fail closed for empty, forged, unknown and missing slots",()=>{const a=createArchitectureAuthority({registries:{slotRegistry:registry()},coreUserValueMapping:{status:"mapped",patternIds:["recipe"]}});assert.equal(slotRegistryCoverageProof({authority:a}).complete,true);assert.equal(capabilityCoverageProof({authority:a,requirementFingerprint:"fp",complete:true}).complete,false);a.ledgers.coreUserValueMapping={status:"mapped",patternIds:[]};assert.equal(slotRegistryCoverageProof({authority:a}).complete,false);a.ledgers.coreUserValueMapping={status:"mapped",patternIds:["fake"]};assert.equal(slotRegistryCoverageProof({authority:a}).complete,false);a.ledgers.coreUserValueMapping={status:"mapped",patternIds:["recipe"]};a.registries.slotRegistry.semanticRegistryVersion="fake";assert.equal(slotRegistryCoverageProof({authority:a}).complete,false);assert.equal(slotRegistryCoverageProof({authority:createArchitectureAuthority({registries:{slotRegistry:DEFAULT_SLOT_REGISTRY}})}).complete,false);});

test("claim coverage enumerates sources from ledgers and requires current validated evidence",()=>{const a=evidence();a.registries.claimTypes=[{claimTypeId:"required",required:true,sourceKinds:["capability","decision","core_invariant","primary_flow"]}];a.ledgers.capabilities.set("cap",{id:"cap",currentness:"current",blocking:true,scopeKey:"s"});a.ledgers.coreInvariants.set("inv",{id:"inv",currentness:"current",scopeKey:"s"});a.ledgers.primaryFlows.set("flow",{id:"flow",currentness:"current",scopeKey:"s"});a.ledgers.revisions.set("dec",{revisionId:"dec",currentness:"current",classification:"product_requirement",settlement:"settled",scopeKey:"s"});for(const id of ["cap","inv","flow","dec"])a.ledgers.claims.set(`c-${id}`,{claimId:`c-${id}`,claimTypeId:"required",sourceIds:[id],scopeKey:"s",currentness:"current",evidenceEdgeIds:["e"]});assert.equal(claimCoverageProof({authority:a,claimSetFingerprint:"f"}).complete,true);a.ledgers.claims.delete("c-cap");assert.equal(claimCoverageProof({authority:a,claimSetFingerprint:"f",sources:[]}).complete,false);a.ledgers.claims.set("c-cap",{claimId:"c-cap",claimTypeId:"required",sourceIds:["cap"],scopeKey:"s",currentness:"current",evidenceEdgeIds:["fake"]});assert.equal(claimCoverageProof({authority:a,claimSetFingerprint:"f"}).complete,false);});

test("audit requires a current successful matching audit and never trusts an absent/unknown result",()=>{const a=createArchitectureAuthority();assert.notEqual(auditTerminalState({authority:a,auditId:"x",requirementFingerprint:"fp"}).state,"passed");a.ledgers.audits.set("x",{auditId:"x",currentness:"current",requirementFingerprint:"fp",attempts:1,maxAttempts:2,outcome:"passed",errorKind:"unknown",rejectedGapFingerprints:[]});assert.notEqual(auditTerminalState({authority:a,auditId:"x",requirementFingerprint:"fp"}).state,"passed");a.ledgers.audits.set("x",{auditId:"x",currentness:"current",requirementFingerprint:"fp",attempts:1,maxAttempts:2,outcome:"passed",proposedGapFingerprint:"g",rejectedGapFingerprints:["g"]});assert.notEqual(auditTerminalState({authority:a,auditId:"x",requirementFingerprint:"fp"}).state,"passed");a.ledgers.audits.set("x",{auditId:"x",currentness:"current",requirementFingerprint:"fp",attempts:1,maxAttempts:2,outcome:"passed",rejectedGapFingerprints:[]});assert.equal(auditTerminalState({authority:a,auditId:"x",requirementFingerprint:"fp"}).state,"passed");});

test("fingerprints omit timestamps but retain semantic claim changes",()=>{const s={coreUserValue:{revisionId:"r",value:"v",currentness:"current",createdAt:"a"},actors:[],managedObjects:[],activeCapabilities:[],traitHeads:[],decisionRevisions:[],openBlockingIssues:[],registryVersions:REGISTRY_VERSION_SET},fp=requirementFingerprint(s);assert.equal(fp,requirementFingerprint({...s,coreUserValue:{...s.coreUserValue,createdAt:"b"}}));assert.notEqual(claimSetFingerprint({requirementFingerprint:fp,claims:[{claimId:"c",scopeKey:"a",sourceIds:[],evidenceEdgeIds:[]}],claimTypeRegistryVersion:"v"}),claimSetFingerprint({requirementFingerprint:fp,claims:[{claimId:"c",scopeKey:"b",sourceIds:[],evidenceEdgeIds:[]}],claimTypeRegistryVersion:"v"}));});

test("criticality, stale transaction, migration currentness and SPEC provenance are authoritative",()=>{const a=createArchitectureAuthority({revisions:[{revisionId:"d",criticalityRuleId:"fake"}],artifacts:[{id:"r",kind:"revision",currentness:"current"},{id:"c",kind:"claim",currentness:"current"}],dependencyEdges:[{fromArtifactKind:"revision",fromArtifactId:"r",toArtifactKind:"claim",toArtifactId:"c",dependencyKind:"grounding"}]});assert.equal(resolveCriticality({authority:a,decisionInstanceId:"d",requirementFingerprint:"f"}).blocking,false);a.registries.criticalityRules=[{ruleId:"real",evaluate:()=>true}];a.ledgers.revisions.get("d").criticalityRuleId="real";assert.equal(resolveCriticality({authority:a,decisionInstanceId:"d",requirementFingerprint:"f"}).blocking,true);assert.throws(()=>propagateStaleTransaction({authority:a,changedArtifactId:"revision:r",reevaluate:()=>false}));assert.equal(a.ledgers.artifacts.get("revision:r").currentness,"current");assert.deepEqual(propagateStaleTransaction({authority:a,changedArtifactId:"revision:r"}),["claim:c","revision:r"]);const src={facts:[{key:"u",source:"user_confirmed",revisionId:"u",value:"x"}]},one=migrateV4Context({authority:a,source:src,registryVersionSet:REGISTRY_VERSION_SET}),two=migrateV4Context({authority:a,source:src,registryVersionSet:{...REGISTRY_VERSION_SET,trait:"new"}});assert.equal(a.ledgers.migrations.get(one.record.migrationId).migrationStatus,"superseded");assert.equal(currentMigrationProjection({authority:a,sourceFactFingerprint:two.record.sourceFactFingerprint}).userConfirmedRevisions[0].revisionId,"u");a.ledgers.claims.set("claim",{claimId:"claim",currentness:"current"});assert.equal(validateSpecClaimConformance({authority:a,specElements:[{id:"fr",kind:"functional_requirement",sourceClaimIds:[]}] }).complete,false);assert.equal(validateSpecClaimConformance({authority:a,specElements:[{id:"fr",kind:"functional_requirement",sourceClaimIds:["claim"]}] }).complete,true);assert.throws(()=>validateArtifactDag([{fromArtifactKind:"a",fromArtifactId:"1",toArtifactKind:"a",toArtifactId:"1",dependencyKind:"bad"}]));});
