import test from "node:test";
import assert from "node:assert/strict";
import * as c from "../src/requirements-v5/contracts.js";
const copy = (x) => JSON.parse(JSON.stringify(x));
const registry = () => ({ versionSet: { ...c.REGISTRY_VERSION_SET }, rules: [{ id: "rule:s", version: "1" }, { id: "rule:na", version: "1" }, { id: "rule:ex", version: "1" }, { id: "rule:settle", version: "1" }, { id: "rule:conflict", version: "1" }, { id: "rule:feas", version: "1" }, { id: "rule:graph", version: "1" }], transforms: [{ id: "transform:identity" }, { id: "transform:registered" }], slotTemplates: c.UNIVERSAL_SLOT_TEMPLATES.map((slotTemplateId) => ({ slotTemplateId, satisfactionRuleId: "rule:s", notApplicableRuleId: "rule:na", exclusionRuleId: "rule:ex" })), coreUserValuePatterns: [{ id: "p", universalSlotTemplateIds: [...c.UNIVERSAL_SLOT_TEMPLATES], patternSlotTemplateIds: [] }], capabilityTypes: [{ id: "cap" }], decisionTypes: [{ id: "dec" }], traitTypes: [{ id: "trait" }], claimTypes: [{ id: "claim" }], auditExecutors: [{ id: "audit", version: "1" }], specWriters: [{ id: "writer", version: "1" }], migrationAdapters: [{ id: "migration", version: "1" }], requiredCapabilityKeys: c.UNIVERSAL_SLOT_TEMPLATES.map((x) => `cap:${x}`), requiredDecisionKeys: c.UNIVERSAL_SLOT_TEMPLATES.map((x) => `dec:${x}`), requiredCoreInvariantKeys: ["inv"], requiredPrimaryFlowKeys: ["flow"] });
const fixture = () => {
  const r = registry(); const l = { coreUserValue: { revisionId: "r0", targetId: "t0", evidenceId: "e0", value: "予定を管理する", patternId: "p", scopeKey: "core" }, revisions: [{ id: "r0", type: "revision", text: "予定を管理する", scopeKey: "core", currentness: "current" }], targets: [{ id: "t0", classification: "core_user_value", scopeKey: "core", currentness: "current" }], evidenceEdges: [{ id: "e0", sourceRevisionId: "r0", targetId: "t0", evidenceSpan: "予定を管理する", relation: "explicitly_states", transformRuleId: "transform:identity", scopeKey: "core", derivationDepth: 0, currentness: "current" }], capabilities: [], decisionRevisions: [], claims: [], artifacts: [], issues: [], evaluationProofs: [], auditExecutions: [], decisionSettlementRecords: [], requiredSpecElements: [], migrationRecords: [], actors: [], managedObjects: [], traits: [] };
  for (const slot of c.UNIVERSAL_SLOT_TEMPLATES) { const rid = `r:${slot}`; const tid = `t:${slot}`; const eid = `e:${slot}`; const cap = `cap:${slot}`; const dec = `dec:${slot}`; l.revisions.push({ id: rid, instanceId: dec, type: "revision", text: slot, scopeKey: "g", currentness: "current" }); l.targets.push({ id: tid, classification: "product_requirement", scopeKey: "g", currentness: "current" }); l.evidenceEdges.push({ id: eid, sourceRevisionId: rid, targetId: tid, evidenceSpan: slot, relation: "explicitly_states", transformRuleId: "transform:identity", scopeKey: "g", derivationDepth: 0, currentness: "current" }); l.capabilities.push({ id: cap, key: slot, targetId: tid, evidenceId: eid, scopeKey: "g", currentness: "current" }); l.decisionRevisions.push({ id: dec, instanceId: dec, targetId: tid, evidenceId: eid, value: slot, scopeKey: "g", currentness: "current" }); l.claims.push({ id: `claim:${cap}`, sourceId: cap, typeId: "claim", targetId: tid, evidenceId: eid, scopeKey: "g", currentness: "current" }, { id: `claim:${dec}`, sourceId: dec, typeId: "claim", targetId: tid, evidenceId: eid, scopeKey: "g", currentness: "current" }); l.evaluationProofs.push(); }
  l.coreInvariants = [{ id: "inv", targetId: "t0", evidenceId: "e0", scopeKey: "core", currentness: "current" }]; l.primaryFlows = [{ id: "flow", targetId: "t0", evidenceId: "e0", scopeKey: "core", currentness: "current" }]; l.claims.push({ id: "claim:inv", sourceId: "inv", typeId: "claim", targetId: "t0", evidenceId: "e0", scopeKey: "core", currentness: "current" }, { id: "claim:flow", sourceId: "flow", typeId: "claim", targetId: "t0", evidenceId: "e0", scopeKey: "core", currentness: "current" });
  const a = c.createVerifierAuthority({ registry: r, ledger: l }); const fp = c.requirementFingerprint(a); l.decisionSettlementRecords.push(...c.UNIVERSAL_SLOT_TEMPLATES.map((slot) => ({ decisionId: `dec:${slot}`, status: "settled", ruleId: "rule:settle", requirementFingerprint: fp }))); l.evaluationProofs.push(...["conflict", "feasibility", "graph_fixpoint"].map((kind, i) => ({ kind, status: "resolved", evaluatorRuleId: ["rule:conflict", "rule:feas", "rule:graph"][i], requirementFingerprint: fp }))); const closures = c.UNIVERSAL_SLOT_TEMPLATES.map((slot) => ({ slotTemplateId: slot, status: "satisfied", evidenceId: `e:${slot}`, targetId: `t:${slot}`, scopeKey: "g", ruleId: "rule:s", ruleVersion: "1", requirementFingerprint: fp })); const provisional = { proofId: "p1", requirementFingerprint: fp, capabilityCoverageProof: { requirementFingerprint: fp, closures } }; const claim = { claimSetFingerprint: c.claimSetFingerprint(a) }; l.auditExecutions.push({ auditId: "a1", executionId: "x1", executorId: "audit", executorVersion: "1", outcome: "passed", completed: true, requirementFingerprint: fp, provisionalProofId: "p1", blockingGapIds: [] }); l.requiredSpecElements.push(...l.claims.map((x, i) => ({ id: `s${i}`, kind: "functional_requirement", sourceId: x.sourceId }))); const artifact = { writerId: "writer", writerVersion: "1", requirementFingerprint: fp, artifactFingerprint: "artifact", elements: l.requiredSpecElements.map((x) => ({ ...x, sourceClaimIds: [`claim:${x.sourceId}`] })) }; const audit = { auditId: "a1", executionId: "x1" }; const final = { provisionalProofId: "p1", auditExecutionId: "x1", completionCandidateFingerprint: c.completionCandidateFingerprint(a, "a1") }; return { r, l, a, provisional, claim, audit, artifact, final }; };
const valid = (x) => c.validateFinalCompletionProof(x.a, { provisionalProof: x.provisional, claimCoverageProof: x.claim, auditProof: x.audit, specArtifact: x.artifact, finalProof: x.final });

test("production raw inputs are always blocked without a semantic authority", () => { const a = c.createArchitectureAuthority(); for (const [i, text] of ["xx", "aa", "0", "false", "single_actor", ""].entries()) c.submitRawUserAnswer({ authority: a, event: { eventId: `x${i}`, text } }); assert.equal(c.finalCompletionProof({ authority: a }).status, "blocked_missing_authority"); });
test("complete synthetic fixture is eligible and candidate proof cannot redefine facts", () => { const x = fixture(); assert.equal(valid(x).eligible, true); x.provisional.capabilityCoverageProof.closures[0].status = "not_applicable"; x.provisional.capabilityCoverageProof.closures[0].ruleId = "fake"; assert.equal(valid(x).eligible, false); });
test("evidence structure rejects stale, unknown relation, missing parent and fake transform", () => { for (const mutate of [(x) => { x.l.evidenceEdges[0].currentness = "stale"; }, (x) => { x.l.evidenceEdges[0].relation = "fake"; }, (x) => { x.l.evidenceEdges[1].relation = "directly_entails"; x.l.evidenceEdges[1].transformRuleId = "transform:registered"; x.l.evidenceEdges[1].derivationDepth = 1; }, (x) => { x.l.evidenceEdges[0].transformRuleId = "fake"; }]) { const x = fixture(); mutate(x); assert.equal(valid(x).eligible, false); } });
test("proof chain rejects fake settlement, missing evaluators, fake audit, omitted required sources, and reduced SPEC", () => { for (const mutate of [(x) => { x.l.decisionSettlementRecords[0].status = "settled"; x.l.decisionSettlementRecords[0].ruleId = "fake"; }, (x) => { x.l.evaluationProofs.splice(0); }, (x) => { x.audit.executionId = "fake"; }, (x) => { x.l.claims.pop(); }, (x) => { x.artifact.elements.splice(1); }]) { const x = fixture(); mutate(x); assert.equal(valid(x).eligible, false); } });
test("revision kernel rejects supersede cycles and atomically rolls back cycles", () => { assert.equal(c.validateRevisionInvariants({ revisions: [{ id: "r1", instanceId: "d", currentness: "stale", supersedesRevisionId: "r2" }, { id: "r2", instanceId: "d", currentness: "current", supersedesRevisionId: "r1" }] }).eligible, false); const k = c.createTransactionKernel(); const t = c.beginTransaction(k); c.proposeRevision(t, { id: "r", instanceId: "d", currentness: "current" }); c.proposeDependency(t, { fromId: "r", toId: "a", type: "depends" }); c.proposeDependency(t, { fromId: "a", toId: "r", type: "depends" }); assert.equal(c.commitTransaction(t).committed, false); assert.equal(c.transactionSnapshot(k).revisions.length, 0); });
test("migration verifier rejects replay and non-current projection", () => { const x = fixture(); const rec = { sourceContextVersion: "v4", targetContextVersion: "v5", sourceFactFingerprint: "s", registryVersionSet: { ...c.REGISTRY_VERSION_SET }, adapterId: "migration", adapterVersion: "1", sourceProvenance: "verified", migrationStatus: "ok", migrationWarnings: [] }; rec.migrationId = c.migrationRecordId(rec); x.l.migrationRecords.push(rec); assert.equal(c.validateMigrationRecord(x.a, { record: rec, projections: [{ migrationId: rec.migrationId, sourceFactFingerprint: "s", compatible: true, currentness: "current" }] }).eligible, true); assert.equal(c.validateMigrationRecord(x.a, { record: rec, projections: [] }).eligible, false); });
