/** v5 PR0 Contract Kernel. No production semantic producer lives here. */
import { createHash } from "node:crypto";

export const REGISTRY_VERSION_SET = Object.freeze({ decisionType: "v5-pr0.5", capabilityType: "v5-pr0.5", trait: "v5-pr0.5", coreUserValuePattern: "v5-pr0.5", slotTemplate: "v5-pr0.5", criticalityRule: "v5-pr0.5", claimType: "v5-pr0.5", auditRule: "v5-pr0.5", migrationAdapter: "v5-pr0.5" });
export const UNIVERSAL_SLOT_TEMPLATES = Object.freeze(["actor_participation", "primary_interaction", "required_input", "required_output", "success_observability", "state_continuity", "external_boundary", "failure_observability"]);
export const REQUIRED_SPEC_ELEMENT_KINDS = Object.freeze(["functional_requirement", "data_model_field", "state_transition", "error_handling_rule", "acceptance_criteria", "primary_flow_step", "required_product_paragraph"]);
export const COMPLETION_DEPENDENCY_CHAIN = Object.freeze(["revision", "claim", "coverage_proof", "provisional_proof", "audit_proof", "final_completion_proof"]);
const RELATIONS = Object.freeze({ explicitly_states: Object.freeze({ sourceType: "revision", targetTypes: ["core_user_value", "product_requirement"], parent: "forbidden", maxDepth: 0, transformRuleId: "transform:identity", version: "1" }), directly_entails: Object.freeze({ sourceType: "revision", targetTypes: ["product_requirement"], parent: "required", parentRelations: ["explicitly_states"], maxDepth: 1, transformRuleId: "transform:registered", version: "1" }) });
const AUTH = new WeakMap(); const KERNEL = new WeakMap();
const stable = (v) => Array.isArray(v) ? v.map(stable) : v && typeof v === "object" ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, stable(v[k])])) : v;
const hash = (v) => createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");
const snapshot = (v) => deepFreeze(JSON.parse(JSON.stringify(v)));
const clone = (v) => JSON.parse(JSON.stringify(v));
const deepFreeze = (v) => { if (!v || typeof v !== "object" || Object.isFrozen(v)) return v; Object.freeze(v); Object.values(v).forEach(deepFreeze); return v; };
const arr = (v) => Array.isArray(v) ? v : [];
const map = (v) => new Map(arr(v).map((x) => [x.id, x]));
const current = (v) => v?.currentness === "current";
const out = (errors, extra = {}) => Object.freeze({ eligible: errors.length === 0, status: errors.length ? "blocked_invariant" : "eligible", errors: [...new Set(errors)].sort(), ...extra });
const versions = (v) => JSON.stringify(stable(v)) === JSON.stringify(stable(REGISTRY_VERSION_SET));
const rawHash = (e) => hash({ eventId: e.eventId, type: e.type, text: e.text ?? "", questionId: e.questionId ?? null });

const coll = (v) => v === null ? { presence: "null", values: null } : Array.isArray(v) ? { presence: "array", values: [...new Set(v)].sort() } : { presence: "missing", values: null };
export const canonicalCapabilityKey = (key) => ({ capabilityTypeId: key.capabilityTypeId, parentCapabilityInstanceId: key.parentCapabilityInstanceId ?? null, managedObjectIds: coll(key.managedObjectIds), actorIds: coll(key.actorIds), phaseKindId: key.phaseKindId ?? null });
export const canonicalDecisionKey = (key, definition = null) => { const value = { decisionTypeId: key.decisionTypeId, capabilityInstanceId: key.capabilityInstanceId ?? null, managedObjectIds: coll(key.managedObjectIds), actorIds: coll(key.actorIds), phaseKindId: key.phaseKindId ?? null }; if (!value.capabilityInstanceId && definition?.globalScopeAllowed !== true) throw new Error("decision scope requires a capability instance"); return value; };
export const capabilityInstanceId = (key) => `cap:${hash(canonicalCapabilityKey(key))}`;
export const decisionInstanceId = (key, definition) => `dec:${hash(canonicalDecisionKey(key, definition))}`;

/** Production ingress: raw events never become semantic facts in PR0. */
export function createArchitectureAuthority() { const a = Object.freeze({ kind: "v5-pr0-production-authority" }); AUTH.set(a, { raw: new Map(), production: true }); return a; }
const stateOf = (a) => { const s = AUTH.get(a); if (!s) throw new Error("invalid authority"); return s; };
const record = (a, e, type) => { const s = stateOf(a); if (!e || !e.eventId || typeof e.text !== "string") throw new Error("invalid raw event"); const fact = { eventId: e.eventId, type, text: e.text, questionId: e.questionId ?? null, digest: rawHash({ ...e, type }) }; const old = s.raw.get(e.eventId); if (old && old.digest !== fact.digest) throw new Error("raw event replay was modified"); if (!old) s.raw.set(e.eventId, Object.freeze(fact)); return { accepted: true, replay: Boolean(old), status: "blocked_missing_authority", reasonCodes: ["semantic_authority_unavailable"] }; };
export const submitRawInitialInput = ({ authority, event }) => record(authority, event, "initial_input");
export const submitRawUserAnswer = ({ authority, event }) => record(authority, event, "user_answer");
export const submitExplicitUserConfirmation = ({ authority, event }) => record(authority, event, "user_confirmation");
export const listPendingQuestions = ({ authority }) => { stateOf(authority); return []; };
export const productionCompletionStatus = ({ authority }) => { stateOf(authority); return Object.freeze({ eligible: false, status: "blocked_missing_authority", reasonCodes: ["semantic_authority_unavailable", "registered_registry_unavailable", "registered_rule_engine_unavailable", "registered_audit_executor_unavailable"] }); };
export const provisionalCompletionProof = productionCompletionStatus; export const finalCompletionProof = productionCompletionStatus; export const requestAuditExecution = productionCompletionStatus; export const auditTerminalState = productionCompletionStatus; export const requestMigration = productionCompletionStatus; export const currentMigrationProjection = ({ authority }) => { stateOf(authority); return null; };

/** Test-only/synthetic Authority fixture: Registry, Ledger and candidate Proof stay separate. */
export function createVerifierAuthority({ registry, ledger }) { const a = Object.freeze({ kind: "v5-pr0-verifier-authority" }); AUTH.set(a, Object.freeze({ registry: snapshot(registry), ledger: snapshot(ledger), production: false })); return a; }
const facts = (authority) => { const s = stateOf(authority); if (s.production) return null; return s; };
const semantic = ({ id, typeId, key, value, scopeKey, evidenceId, instanceId, kind }) => ({ id, typeId: typeId ?? null, key: key ?? null, value: value ?? null, scopeKey: scopeKey ?? null, evidenceId: evidenceId ?? null, instanceId: instanceId ?? null, kind: kind ?? null });
export function requirementFingerprint(authority) { const { registry, ledger } = facts(authority) ?? {}; return hash({ coreUserValue: ledger?.coreUserValue ? { revisionId: ledger.coreUserValue.revisionId, value: ledger.coreUserValue.value, patternId: ledger.coreUserValue.patternId } : null, actors: arr(ledger?.actors).filter(current).map(semantic), managedObjects: arr(ledger?.managedObjects).filter(current).map(semantic), capabilities: arr(ledger?.capabilities).filter(current).map(semantic), traits: arr(ledger?.traits).filter(current).map(semantic), decisions: arr(ledger?.decisionRevisions).filter(current).map(semantic), blockingIssues: arr(ledger?.issues).filter((x) => current(x) && x.blocking).map(semantic), registryVersions: registry?.versionSet ?? null }); }
export function claimSetFingerprint(authority) { const { ledger } = facts(authority) ?? {}; return hash({ requirementFingerprint: requirementFingerprint(authority), claims: arr(ledger?.claims).filter(current).map(({ id, sourceId, typeId, evidenceId, scopeKey }) => ({ id, sourceId, typeId, evidenceId, scopeKey })), claimTypeVersion: facts(authority)?.registry?.versionSet?.claimType ?? null }); }
export const completionCandidateFingerprint = (authority, auditId) => { const record = arr(facts(authority)?.ledger?.auditExecutions).find((x) => x.auditId === auditId); return hash({ requirementFingerprint: requirementFingerprint(authority), claimSetFingerprint: claimSetFingerprint(authority), auditId, executionId: record?.executionId ?? null, executionArtifactFingerprint: record?.executionArtifactFingerprint ?? null }); };

export function validateRegistryContext(authority) { const f = facts(authority); if (!f) return out(["missing_authority"]); const { registry } = f; const errors = []; if (!versions(registry?.versionSet)) errors.push("registry_version_mismatch"); const rules = new Set(arr(registry?.rules).map((x) => x.id)); const slots = new Set(arr(registry?.slotTemplates).map((x) => x.slotTemplateId)); for (const id of UNIVERSAL_SLOT_TEMPLATES) if (!slots.has(id)) errors.push(`missing_universal_slot:${id}`); for (const slot of arr(registry?.slotTemplates)) if (!rules.has(slot.satisfactionRuleId) || !rules.has(slot.notApplicableRuleId) || !rules.has(slot.exclusionRuleId)) errors.push(`unresolved_slot_rule:${slot.slotTemplateId}`); if (!arr(registry?.coreUserValuePatterns).length || !arr(registry?.capabilityTypes).length || !arr(registry?.decisionTypes).length || !arr(registry?.traitTypes).length || !arr(registry?.claimTypes).length || !arr(registry?.auditExecutors).length) errors.push("incomplete_registry_universe"); for (const pattern of arr(registry?.coreUserValuePatterns)) for (const id of [...arr(pattern.universalSlotTemplateIds), ...arr(pattern.patternSlotTemplateIds)]) if (!slots.has(id)) errors.push(`uncovered_pattern_slot:${pattern.id}:${id}`); return out(errors); }
const evidenceCurrent = (f, id, targetId, scopeKey) => { const edge = map(f.ledger.evidenceEdges).get(id); const rev = edge && map(f.ledger.revisions).get(edge.sourceRevisionId); const target = edge && map(f.ledger.targets).get(edge.targetId); return Boolean(current(edge) && current(rev) && current(target) && edge.targetId === targetId && edge.scopeKey === scopeKey); };
export function validateEvidenceEdges(authority) { const f = facts(authority); if (!f) return out(["missing_authority"]); const errors = [...validateRegistryContext(authority).errors]; const revisions = map(f.ledger.revisions); const targets = map(f.ledger.targets); const edges = map(f.ledger.evidenceEdges); const transforms = new Set(arr(f.registry.transforms).map((x) => x.id)); for (const edge of arr(f.ledger.evidenceEdges)) { const rule = RELATIONS[edge.relation]; const source = revisions.get(edge.sourceRevisionId); const target = targets.get(edge.targetId); if (!current(edge)) errors.push(`stale_evidence:${edge.id}`); if (!current(source)) errors.push(`stale_evidence_source:${edge.id}`); if (!current(target)) errors.push(`stale_evidence_target:${edge.id}`); if (!rule) { errors.push(`unknown_evidence_relation:${edge.id}`); continue; } if (source?.type !== rule.sourceType || !rule.targetTypes.includes(target?.classification)) errors.push(`evidence_relation_type_mismatch:${edge.id}`); if (edge.transformRuleId !== rule.transformRuleId || !transforms.has(edge.transformRuleId)) errors.push(`unregistered_transform:${edge.id}`); if (edge.evidenceSpan !== source?.text || edge.scopeKey !== source?.scopeKey || edge.scopeKey !== target?.scopeKey) errors.push(`evidence_structure_mismatch:${edge.id}`); if ((edge.derivationDepth ?? 0) > rule.maxDepth) errors.push(`evidence_depth_exceeded:${edge.id}`); if (rule.parent === "required" && (!edge.parentEdgeId || !edges.has(edge.parentEdgeId) || !rule.parentRelations.includes(edges.get(edge.parentEdgeId).relation))) errors.push(`missing_or_invalid_parent:${edge.id}`); if (rule.parent === "forbidden" && edge.parentEdgeId) errors.push(`forbidden_parent:${edge.id}`); } return out(errors); }

const requiredUniverse = (f) => ({ capabilities: arr(f.registry.requiredCapabilityKeys), decisions: arr(f.registry.requiredDecisionKeys), slots: arr(f.registry.coreUserValuePatterns).find((p) => p.id === f.ledger.coreUserValue?.patternId), specElements: arr(f.ledger.requiredSpecElements) });
export function validateCapabilityCoverageProof(authority, proof) { const f = facts(authority); if (!f) return out(["missing_authority"]); const errors = [...validateEvidenceEdges(authority).errors]; const u = requiredUniverse(f); if (proof?.requirementFingerprint !== requirementFingerprint(authority)) errors.push("requirement_fingerprint_mismatch"); if (!u.slots || !evidenceCurrent(f, f.ledger.coreUserValue?.evidenceId, f.ledger.coreUserValue?.targetId, f.ledger.coreUserValue?.scopeKey)) errors.push("core_user_value_unmapped_or_ungrounded"); const slots = new Map(arr(proof?.closures).map((x) => [x.slotTemplateId, x])); const rules = new Set(arr(f.registry.rules).map((x) => x.id)); for (const id of [...arr(u.slots?.universalSlotTemplateIds), ...arr(u.slots?.patternSlotTemplateIds)]) { const x = slots.get(id); if (!x) { errors.push(`missing_slot_closure:${id}`); continue; } if (!rules.has(x.ruleId) || x.ruleVersion !== "1" || x.requirementFingerprint !== requirementFingerprint(authority)) errors.push(`invalid_slot_rule:${id}`); if (x.status === "satisfied" && !evidenceCurrent(f, x.evidenceId, x.targetId, x.scopeKey)) errors.push(`invalid_slot_evidence:${id}`); if (["not_applicable", "explicitly_not_required"].includes(x.status) && (!x.evidenceId || !evidenceCurrent(f, x.evidenceId, x.targetId, x.scopeKey))) errors.push(`unproven_slot_closure:${id}`); if (!["satisfied", "not_applicable", "explicitly_not_required"].includes(x.status)) errors.push(`unresolved_slot:${id}`); } return out(errors); }
export function validateClaimCoverageProof(authority, proof) { const f = facts(authority); if (!f) return out(["missing_authority"]); const errors = []; if (proof?.claimSetFingerprint !== claimSetFingerprint(authority)) errors.push("claim_set_fingerprint_mismatch"); const types = new Set(arr(f.registry.claimTypes).map((x) => x.id)); const sources = [...arr(f.registry.requiredCapabilityKeys), ...arr(f.registry.requiredDecisionKeys), ...arr(f.registry.requiredCoreInvariantKeys), ...arr(f.registry.requiredPrimaryFlowKeys)]; for (const id of sources) { const claim = arr(f.ledger.claims).find((x) => current(x) && x.sourceId === id); if (!claim) errors.push(`missing_required_claim:${id}`); else if (!types.has(claim.typeId) || !evidenceCurrent(f, claim.evidenceId, claim.targetId, claim.scopeKey)) errors.push(`invalid_claim:${id}`); } return out(errors); }
export function validateProvisionalCompletionProof(authority, proof) { const f = facts(authority); if (!f) return out(["missing_authority"]); const errors = [...validateCapabilityCoverageProof(authority, proof?.capabilityCoverageProof).errors]; if (proof?.requirementFingerprint !== requirementFingerprint(authority)) errors.push("provisional_fingerprint_mismatch"); const settlement = new Map(arr(f.ledger.decisionSettlementRecords).map((x) => [x.decisionId, x])); for (const id of arr(f.registry.requiredDecisionKeys)) { const x = settlement.get(id); if (!x || !["settled", "delegated"].includes(x.status) || x.requirementFingerprint !== requirementFingerprint(authority) || !f.registry.rules.some((r) => r.id === x.ruleId)) errors.push(`unproven_decision_settlement:${id}`); } for (const kind of ["conflict", "feasibility", "graph_fixpoint"]) { const x = arr(f.ledger.evaluationProofs).find((p) => p.kind === kind && p.requirementFingerprint === requirementFingerprint(authority)); if (!x || x.status !== "resolved" || !f.registry.rules.some((r) => r.id === x.evaluatorRuleId)) errors.push(`missing_or_invalid_${kind}_proof`); } if (arr(f.ledger.artifacts).some((x) => x.blocking && x.currentness === "stale")) errors.push("stale_blocking_artifact"); return out(errors); }
export function validateAuditProof(authority, auditProof, provisionalProof) { const f = facts(authority); if (!f) return out(["missing_authority"]); const record = arr(f.ledger.auditExecutions).find((x) => x.executionId === auditProof?.executionId); const executor = arr(f.registry.auditExecutors).find((x) => x.id === record?.executorId); const errors = []; if (!record || !executor || executor.version !== record.executorVersion || record.outcome !== "passed" || record.completed !== true) errors.push("missing_or_invalid_audit_execution"); if (record?.requirementFingerprint !== requirementFingerprint(authority) || record?.provisionalProofId !== provisionalProof?.proofId || arr(record?.blockingGapIds).length) errors.push("stale_or_gapped_audit"); if (auditProof?.executionId !== record?.executionId || auditProof?.auditId !== record?.auditId) errors.push("audit_reference_mismatch"); return out(errors); }
export function validateSpecClaimConformance(authority, artifact) { const f = facts(authority); if (!f) return out(["missing_authority"]); const errors = []; const writer = arr(f.registry.specWriters).find((x) => x.id === artifact?.writerId && x.version === artifact?.writerVersion); if (!writer || artifact?.requirementFingerprint !== requirementFingerprint(authority) || !artifact?.artifactFingerprint) errors.push("missing_or_stale_spec_artifact"); const actual = new Map(arr(artifact?.elements).map((x) => [x.id, x])); const claims = new Set(arr(f.ledger.claims).filter(current).map((x) => x.id)); for (const req of arr(f.ledger.requiredSpecElements)) { const e = actual.get(req.id); if (!e || e.kind !== req.kind || !arr(e.sourceClaimIds).length || arr(e.sourceClaimIds).some((id) => !claims.has(id))) errors.push(`spec_claim_conformance_failed:${req.id}`); } return out(errors); }
/**
 * Completion artifacts are not optional candidate metadata.  The authoritative
 * ledger must contain the complete typed dependency chain so a caller cannot
 * omit an edge and thereby prevent stale propagation from reaching Final.
 */
export function validateCompletionDependencyDAG({ artifacts = [], dependencies = [] } = {}) { const errors = []; const byId = map(artifacts); const byKind = new Map(); for (const artifact of arr(artifacts)) { if (!artifact.id || !COMPLETION_DEPENDENCY_CHAIN.includes(artifact.kind)) errors.push(`invalid_completion_artifact:${artifact.id ?? "unknown"}`); else byKind.set(artifact.kind, [...(byKind.get(artifact.kind) ?? []), artifact]); if (artifact.currentness !== "current") errors.push(`stale_completion_artifact:${artifact.id ?? "unknown"}`); }
  for (const kind of COMPLETION_DEPENDENCY_CHAIN) if (!byKind.has(kind)) errors.push(`missing_completion_artifact:${kind}`);
  for (let index = 0; index < COMPLETION_DEPENDENCY_CHAIN.length - 1; index += 1) { const fromKind = COMPLETION_DEPENDENCY_CHAIN[index]; const toKind = COMPLETION_DEPENDENCY_CHAIN[index + 1]; const from = byKind.get(fromKind) ?? []; const to = byKind.get(toKind) ?? []; for (const target of to) { const edge = arr(dependencies).find((candidate) => candidate.type === "completion_dependency" && candidate.toId === target.id && from.some((source) => source.id === candidate.fromId)); if (!edge || !byId.has(edge.fromId) || !byId.has(edge.toId)) errors.push(`missing_required_completion_dependency:${fromKind}->${toKind}:${target.id}`); }
  }
  return out(errors);
}
export function validateFinalCompletionProof(authority, { provisionalProof, claimCoverageProof, auditProof, specArtifact, finalProof }) { const f = facts(authority); const errors = [...validateProvisionalCompletionProof(authority, provisionalProof).errors, ...validateClaimCoverageProof(authority, claimCoverageProof).errors, ...validateAuditProof(authority, auditProof, provisionalProof).errors, ...validateSpecClaimConformance(authority, specArtifact).errors, ...validateCompletionDependencyDAG({ artifacts: f?.ledger?.artifacts, dependencies: f?.ledger?.dependencies }).errors]; const expected = completionCandidateFingerprint(authority, auditProof?.auditId); if (finalProof?.completionCandidateFingerprint !== expected || finalProof?.provisionalProofId !== provisionalProof?.proofId || finalProof?.auditExecutionId !== auditProof?.executionId) errors.push("final_proof_chain_mismatch"); return out(errors); }

export const migrationRecordId = (r) => `migration:${hash({ sourceContextVersion: r.sourceContextVersion, targetContextVersion: r.targetContextVersion, sourceFactFingerprint: r.sourceFactFingerprint, registryVersionSet: r.registryVersionSet, adapterId: r.adapterId, adapterVersion: r.adapterVersion })}`;
export function validateMigrationRecord(authority, { record, projections = [] }) { const f = facts(authority); if (!f) return out(["missing_authority"]); const adapter = arr(f.registry.migrationAdapters).find((x) => x.id === record?.adapterId && x.version === record?.adapterVersion); const errors = []; if (!adapter || !versions(record?.registryVersionSet) || !record?.sourceProvenance || record.migrationId !== migrationRecordId(record)) errors.push("invalid_migration_identity_or_provenance"); const same = arr(f.ledger.migrationRecords).filter((x) => x.sourceFactFingerprint === record?.sourceFactFingerprint && x.targetContextVersion === record?.targetContextVersion); if (same.length !== 1 || same[0].migrationId !== record?.migrationId) errors.push("migration_replay_or_idempotency_violation"); const current = arr(projections).filter((x) => x.currentness === "current" && x.sourceFactFingerprint === record?.sourceFactFingerprint); if (current.length !== 1 || current[0].migrationId !== record?.migrationId || current.some((x) => x.compatible !== true)) errors.push("invalid_current_migration_projection"); return out(errors); }

export function validateRevisionInvariants({ revisions, dependencies = [] }) { const errors = []; const heads = new Map(); const byRevision = map(revisions); for (const r of arr(revisions)) { if (!r.id || !r.instanceId) errors.push("invalid_revision_identity"); if (current(r)) heads.set(r.instanceId, [...(heads.get(r.instanceId) ?? []), r.id]); } for (const [id, xs] of heads) if (xs.length !== 1) errors.push(`multiple_current_heads:${id}`); const walk = (id, seen = new Set()) => { const r = byRevision.get(id); if (!r?.supersedesRevisionId) return false; if (seen.has(id)) return true; seen.add(id); return walk(r.supersedesRevisionId, seen); }; if (arr(revisions).some((r) => walk(r.id))) errors.push("supersede_cycle"); const graph = new Map(); for (const e of arr(dependencies)) { if (!e.fromId || !e.toId || !e.type) errors.push("invalid_dependency_edge"); graph.set(e.fromId, [...(graph.get(e.fromId) ?? []), e.toId]); } const visit = (id, path = new Set(), done = new Set()) => { if (path.has(id)) return true; if (done.has(id)) return false; path.add(id); const hit = (graph.get(id) ?? []).some((x) => visit(x, path, done)); path.delete(id); done.add(id); return hit; }; if ([...graph.keys()].some((x) => visit(x))) errors.push("artifact_dependency_cycle"); return out(errors); }
export function createTransactionKernel({ revisions = [], dependencies = [], artifacts = [] } = {}) { const k = Object.freeze({ kind: "v5-pr0-transaction-kernel" }); KERNEL.set(k, { version: 0, revisions: clone(revisions), dependencies: clone(dependencies), artifacts: clone(artifacts) }); return k; }
const kernel = (k) => { const s = KERNEL.get(k); if (!s) throw new Error("invalid transaction kernel"); return s; };
export const beginTransaction = (k) => { const s = kernel(k); return { kernel: k, baseVersion: s.version, revisions: clone(s.revisions), dependencies: clone(s.dependencies), artifacts: clone(s.artifacts), closed: false }; };
export const proposeRevision = (t, x) => { if (t.closed) throw new Error("closed transaction"); t.revisions.push({ ...x }); };
export const supersedeRevision = (t, previousRevisionId, nextRevision) => { if (t.closed) throw new Error("closed transaction"); const previous = t.revisions.find((revision) => revision.id === previousRevisionId && current(revision)); if (!previous) throw new Error("current revision not found"); previous.currentness = "stale"; t.revisions.push({ ...nextRevision, instanceId: nextRevision.instanceId ?? previous.instanceId, currentness: "current", supersedesRevisionId: previous.id }); };
export const proposeDependency = (t, x) => { if (t.closed) throw new Error("closed transaction"); t.dependencies.push({ ...x }); };
export const rollbackTransaction = (t) => { t.closed = true; return Object.freeze({ committed: false, rolledBack: true }); };
export function commitTransaction(t) { const s = kernel(t.kernel); if (t.closed || s.version !== t.baseVersion) { t.closed = true; return Object.freeze({ committed: false, rolledBack: true, errors: ["optimistic_concurrency_conflict"] }); } const revisionValid = validateRevisionInvariants(t); const hasCompletionArtifact = t.artifacts.some((artifact) => COMPLETION_DEPENDENCY_CHAIN.includes(artifact.kind)); const completionDagValid = hasCompletionArtifact ? validateCompletionDependencyDAG(t) : out([]); const errors = [...revisionValid.errors, ...completionDagValid.errors]; if (errors.length) { t.closed = true; return Object.freeze({ committed: false, rolledBack: true, errors: [...new Set(errors)].sort() }); } const priorCurrent = new Set(s.revisions.filter(current).map((revision) => revision.id)); const nextCurrent = new Set(t.revisions.filter(current).map((revision) => revision.id)); const changed = new Set([...priorCurrent].filter((id) => !nextCurrent.has(id))); const stale = new Set(changed); const visit = (id) => t.dependencies.filter((edge) => edge.fromId === id).forEach((edge) => { if (!stale.has(edge.toId)) { stale.add(edge.toId); visit(edge.toId); } }); changed.forEach(visit); s.revisions = clone(t.revisions); s.dependencies = clone(t.dependencies); s.artifacts = t.artifacts.map((artifact) => stale.has(artifact.id) ? { ...artifact, currentness: "stale" } : artifact); s.version += 1; t.closed = true; return Object.freeze({ committed: true, staleArtifactIds: [...stale].sort(), version: s.version }); }
export const transactionSnapshot = (k) => { const s = kernel(k); return Object.freeze({ version: s.version, revisions: clone(s.revisions), dependencies: clone(s.dependencies), artifacts: clone(s.artifacts) }); };
